declare namespace NodeJS {
  interface Process {
    // Declare the type of `process.pkg`.
    // When Node.js is running from an executable generated by `vercel/pkg`,
    // `process.pkg` is defined.
    // The presence or absence of `process.pkg` indicates whether the
    // application is running from an executable generated by `vercel/pkg`.
    // However, since the type of `process.pkg` is not declared, it causes
    // a type error in Typescript.
    // To avoid Typescript errors, a type definition for `process.pkg` is
    // provided.
    // See: https://github.com/vercel/pkg/issues/1040
    readonly pkg: unknown;
  }
}
